/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LeadLineNotiRouteImport } from './routes/LeadLineNoti'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicMessagesRouteImport } from './routes/api.public.messages'
import { Route as ApiPublicLeadsRouteImport } from './routes/api.public.leads'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadLineNotiRoute = LeadLineNotiRouteImport.update({
  id: '/LeadLineNoti',
  path: '/LeadLineNoti',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMessagesRoute = ApiPublicMessagesRouteImport.update({
  id: '/api/public/messages',
  path: '/api/public/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadsRoute = ApiPublicLeadsRouteImport.update({
  id: '/api/public/leads',
  path: '/api/public/leads',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/LeadLineNoti': typeof LeadLineNotiRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/api/public/messages': typeof ApiPublicMessagesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/LeadLineNoti': typeof LeadLineNotiRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/api/public/messages': typeof ApiPublicMessagesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/LeadLineNoti': typeof LeadLineNotiRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/api/public/messages': typeof ApiPublicMessagesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/LeadLineNoti'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/api/public/leads'
    | '/api/public/messages'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/LeadLineNoti'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/api/public/leads'
    | '/api/public/messages'
  id:
    | '__root__'
    | '/'
    | '/LeadLineNoti'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/api/public/leads'
    | '/api/public/messages'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeadLineNotiRoute: typeof LeadLineNotiRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ApiPublicLeadsRoute: typeof ApiPublicLeadsRoute
  ApiPublicMessagesRoute: typeof ApiPublicMessagesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/LeadLineNoti': {
      id: '/LeadLineNoti'
      path: '/LeadLineNoti'
      fullPath: '/LeadLineNoti'
      preLoaderRoute: typeof LeadLineNotiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/messages': {
      id: '/api/public/messages'
      path: '/api/public/messages'
      fullPath: '/api/public/messages'
      preLoaderRoute: typeof ApiPublicMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leads': {
      id: '/api/public/leads'
      path: '/api/public/leads'
      fullPath: '/api/public/leads'
      preLoaderRoute: typeof ApiPublicLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeadLineNotiRoute: LeadLineNotiRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ApiPublicLeadsRoute: ApiPublicLeadsRoute,
  ApiPublicMessagesRoute: ApiPublicMessagesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
