/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VvsEmergencyTradesRouteImport } from './routes/vvs-emergency-trades'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as MissadeSamtalAuditRouteImport } from './routes/missade-samtal-audit'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as DentalClinicsRouteImport } from './routes/dental-clinics'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AnvandningsfallNicheRouteImport } from './routes/anvandningsfall/$niche'
import { Route as AuthenticatedLeadLineNotiRouteImport } from './routes/_authenticated/LeadLineNoti'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicMessagesRouteImport } from './routes/api.public.messages'
import { Route as ApiPublicLeadsRouteImport } from './routes/api.public.leads'
import { Route as ApiPublicAuditSubmissionsRouteImport } from './routes/api.public.audit-submissions'
import { Route as AiTelefonistNicheCityRouteImport } from './routes/ai-telefonist/$niche.$city'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const VvsEmergencyTradesRoute = VvsEmergencyTradesRouteImport.update({
  id: '/vvs-emergency-trades',
  path: '/vvs-emergency-trades',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const MissadeSamtalAuditRoute = MissadeSamtalAuditRouteImport.update({
  id: '/missade-samtal-audit',
  path: '/missade-samtal-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const DentalClinicsRoute = DentalClinicsRouteImport.update({
  id: '/dental-clinics',
  path: '/dental-clinics',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AnvandningsfallNicheRoute = AnvandningsfallNicheRouteImport.update({
  id: '/anvandningsfall/$niche',
  path: '/anvandningsfall/$niche',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLeadLineNotiRoute =
  AuthenticatedLeadLineNotiRouteImport.update({
    id: '/LeadLineNoti',
    path: '/LeadLineNoti',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMessagesRoute = ApiPublicMessagesRouteImport.update({
  id: '/api/public/messages',
  path: '/api/public/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadsRoute = ApiPublicLeadsRouteImport.update({
  id: '/api/public/leads',
  path: '/api/public/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuditSubmissionsRoute =
  ApiPublicAuditSubmissionsRouteImport.update({
    id: '/api/public/audit-submissions',
    path: '/api/public/audit-submissions',
    getParentRoute: () => rootRouteImport,
  } as any)
const AiTelefonistNicheCityRoute = AiTelefonistNicheCityRouteImport.update({
  id: '/ai-telefonist/$niche/$city',
  path: '/ai-telefonist/$niche/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dental-clinics': typeof DentalClinicsRoute
  '/experience': typeof ExperienceRoute
  '/missade-samtal-audit': typeof MissadeSamtalAuditRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/vvs-emergency-trades': typeof VvsEmergencyTradesRoute
  '/LeadLineNoti': typeof AuthenticatedLeadLineNotiRoute
  '/anvandningsfall/$niche': typeof AnvandningsfallNicheRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/ai-telefonist/$niche/$city': typeof AiTelefonistNicheCityRoute
  '/api/public/audit-submissions': typeof ApiPublicAuditSubmissionsRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/api/public/messages': typeof ApiPublicMessagesRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dental-clinics': typeof DentalClinicsRoute
  '/experience': typeof ExperienceRoute
  '/missade-samtal-audit': typeof MissadeSamtalAuditRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/vvs-emergency-trades': typeof VvsEmergencyTradesRoute
  '/LeadLineNoti': typeof AuthenticatedLeadLineNotiRoute
  '/anvandningsfall/$niche': typeof AnvandningsfallNicheRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/ai-telefonist/$niche/$city': typeof AiTelefonistNicheCityRoute
  '/api/public/audit-submissions': typeof ApiPublicAuditSubmissionsRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/api/public/messages': typeof ApiPublicMessagesRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dental-clinics': typeof DentalClinicsRoute
  '/experience': typeof ExperienceRoute
  '/missade-samtal-audit': typeof MissadeSamtalAuditRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/vvs-emergency-trades': typeof VvsEmergencyTradesRoute
  '/_authenticated/LeadLineNoti': typeof AuthenticatedLeadLineNotiRoute
  '/anvandningsfall/$niche': typeof AnvandningsfallNicheRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/ai-telefonist/$niche/$city': typeof AiTelefonistNicheCityRoute
  '/api/public/audit-submissions': typeof ApiPublicAuditSubmissionsRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/api/public/messages': typeof ApiPublicMessagesRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/dental-clinics'
    | '/experience'
    | '/missade-samtal-audit'
    | '/partners'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/unsubscribe'
    | '/vvs-emergency-trades'
    | '/LeadLineNoti'
    | '/anvandningsfall/$niche'
    | '/email/unsubscribe'
    | '/ai-telefonist/$niche/$city'
    | '/api/public/audit-submissions'
    | '/api/public/leads'
    | '/api/public/messages'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/dental-clinics'
    | '/experience'
    | '/missade-samtal-audit'
    | '/partners'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/unsubscribe'
    | '/vvs-emergency-trades'
    | '/LeadLineNoti'
    | '/anvandningsfall/$niche'
    | '/email/unsubscribe'
    | '/ai-telefonist/$niche/$city'
    | '/api/public/audit-submissions'
    | '/api/public/leads'
    | '/api/public/messages'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/dental-clinics'
    | '/experience'
    | '/missade-samtal-audit'
    | '/partners'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/unsubscribe'
    | '/vvs-emergency-trades'
    | '/_authenticated/LeadLineNoti'
    | '/anvandningsfall/$niche'
    | '/email/unsubscribe'
    | '/ai-telefonist/$niche/$city'
    | '/api/public/audit-submissions'
    | '/api/public/leads'
    | '/api/public/messages'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DentalClinicsRoute: typeof DentalClinicsRoute
  ExperienceRoute: typeof ExperienceRoute
  MissadeSamtalAuditRoute: typeof MissadeSamtalAuditRoute
  PartnersRoute: typeof PartnersRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  VvsEmergencyTradesRoute: typeof VvsEmergencyTradesRoute
  AnvandningsfallNicheRoute: typeof AnvandningsfallNicheRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  AiTelefonistNicheCityRoute: typeof AiTelefonistNicheCityRoute
  ApiPublicAuditSubmissionsRoute: typeof ApiPublicAuditSubmissionsRoute
  ApiPublicLeadsRoute: typeof ApiPublicLeadsRoute
  ApiPublicMessagesRoute: typeof ApiPublicMessagesRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vvs-emergency-trades': {
      id: '/vvs-emergency-trades'
      path: '/vvs-emergency-trades'
      fullPath: '/vvs-emergency-trades'
      preLoaderRoute: typeof VvsEmergencyTradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missade-samtal-audit': {
      id: '/missade-samtal-audit'
      path: '/missade-samtal-audit'
      fullPath: '/missade-samtal-audit'
      preLoaderRoute: typeof MissadeSamtalAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-clinics': {
      id: '/dental-clinics'
      path: '/dental-clinics'
      fullPath: '/dental-clinics'
      preLoaderRoute: typeof DentalClinicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anvandningsfall/$niche': {
      id: '/anvandningsfall/$niche'
      path: '/anvandningsfall/$niche'
      fullPath: '/anvandningsfall/$niche'
      preLoaderRoute: typeof AnvandningsfallNicheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/LeadLineNoti': {
      id: '/_authenticated/LeadLineNoti'
      path: '/LeadLineNoti'
      fullPath: '/LeadLineNoti'
      preLoaderRoute: typeof AuthenticatedLeadLineNotiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/messages': {
      id: '/api/public/messages'
      path: '/api/public/messages'
      fullPath: '/api/public/messages'
      preLoaderRoute: typeof ApiPublicMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leads': {
      id: '/api/public/leads'
      path: '/api/public/leads'
      fullPath: '/api/public/leads'
      preLoaderRoute: typeof ApiPublicLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/audit-submissions': {
      id: '/api/public/audit-submissions'
      path: '/api/public/audit-submissions'
      fullPath: '/api/public/audit-submissions'
      preLoaderRoute: typeof ApiPublicAuditSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-telefonist/$niche/$city': {
      id: '/ai-telefonist/$niche/$city'
      path: '/ai-telefonist/$niche/$city'
      fullPath: '/ai-telefonist/$niche/$city'
      preLoaderRoute: typeof AiTelefonistNicheCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedLeadLineNotiRoute: typeof AuthenticatedLeadLineNotiRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedLeadLineNotiRoute: AuthenticatedLeadLineNotiRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DentalClinicsRoute: DentalClinicsRoute,
  ExperienceRoute: ExperienceRoute,
  MissadeSamtalAuditRoute: MissadeSamtalAuditRoute,
  PartnersRoute: PartnersRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  VvsEmergencyTradesRoute: VvsEmergencyTradesRoute,
  AnvandningsfallNicheRoute: AnvandningsfallNicheRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  AiTelefonistNicheCityRoute: AiTelefonistNicheCityRoute,
  ApiPublicAuditSubmissionsRoute: ApiPublicAuditSubmissionsRoute,
  ApiPublicLeadsRoute: ApiPublicLeadsRoute,
  ApiPublicMessagesRoute: ApiPublicMessagesRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
